# Generated by Django 5.0.1 on 2024-02-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airhouse', '0003_category_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
            preserve_default=False,
        ),
    ]
