# Generated by Django 5.0.1 on 2024-02-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airhouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invitation_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
